package com.ehb.bestelapp.model;

public enum Categorie {
    BEVESTIGINGSMATERIAAL,
    PBM,
    GEREEDSCHAP,
    TECHNISCHE_ONDERHOUDSMATERIALEN,
    SPECIFIEKE_AQUAFIN_RIOLERINGSGERELATEERDE_TOOLS,
    DIVERSE_VERBRUIKGOEDEREN
}
